title: Operating-Potato's website
email: c04511234@gmail.com
description: "birds. here. read."
author: Charles Ai
baseurl: '/birds'
url: 'https://operating-potato.github.io'
github_username: Operating-Potato
theme: minima
plugins:
  - jekyll-feed
