title: Operating-Potato's website
email: c04511234@gmail.com
description: 
author: Charles Ai
baseurl: '/birds'
url: 'https://operating-potato.github.io'
github_username: Operating-Potato
theme: minima
plugins:
  - jekyll-feed
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "species"
      bird_category: "Birds"
      binomial_name: "Aves sp."
      birdcode: "BIRD"
      minibird-type: "gif"
